### ISSUE TITLE
Failed to setup

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [platysma/hass-vienna-smartmeter#2]
## Version of the custom_component

Latest version

## Describe the bug

After setting it up and entering the credentials I'm getting the following error:

## Debug log

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/vienna_smartmeter/__init__.py", line 47, in async_setup_entry
    await client._refresh_token()
  File "/config/custom_components/vienna_smartmeter/api.py", line 76, in _refresh_token
    "code": await self._get_auth_code(),
  File "/config/custom_components/vienna_smartmeter/api.py", line 55, in _get_auth_code
    action = await self._get_login_action()
  File "/config/custom_components/vienna_smartmeter/api.py", line 50, in _get_login_action
    tree = html.fromstring(resp.content)
  File "/usr/local/lib/python3.9/site-packages/lxml/html/__init__.py", line 874, in fromstring
    is_full_html = _looks_like_full_html_unicode(html)
TypeError: expected string or bytes-like object
```

**Comment by platysma** [comment]
Hi!

Right now, the code in this repo is simply not working. I added an async module to the smartmeter repo some time ago and also updated the code for the hassio integration, but did not commit the changes so far, because I didn't have enough time to get the integration working properly.

I will create a PR with the changes I made and maybe someone can continue from there?

**Comment by drdownload** [comment]
Hi, I wanted to start on the same project but stumbled on yours, I would have used a docker container to send the data over mqtt but HA, but a custom component is of course more elegant ;)

**Comment by fr34kyy** [comment]
@platysma Please update the readme, as it is quite frustrating to follow the instructions only to get the same error message ;)
