### ISSUE TITLE
Error creating sensors

### ISSUE THREAD

**Issue by QGgWW2WhH** [platysma/hass-vienna-smartmeter#26]
## Version of the custom_component

Version 
2c953a3

## Configuration

```yaml
Add your logs here.
```
login detail + 60 as configuration, no yaml configured

## Describe the bug

When booting, there is this error in the log file:

Logger: homeassistant.components.sensor
Source: custom_components/vienna_smartmeter/sensor.py:85
Integration: Sensor (documentation, issues)
First occurred: 21:02:23 (4 occurrences)
Last logged: 21:03:29

    Error adding entities for domain sensor with platform vienna_smartmeter
    Error while setting up vienna_smartmeter platform for sensor

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 442, in _async_add_entity
    if entity.unique_id is not None:
  File "/config/custom_components/vienna_smartmeter/sensor.py", line 85, in unique_id
    meter_id = {self.coordinator.data["zaehlpunkt"]["zaehlpunktnummer"]}
TypeError: 'NoneType' object is not subscriptable

**Comment by platysma** [comment]
This might be linked to the recently introduced log.wien authentication method platysma/vienna-smartmeter#55.

**Comment by splagemann** [comment]
There was recently a new [commit ](https://github.com/platysma/vienna-smartmeter/commit/807662903af4c8a65422cec63813dbbd2d133f55) that fixed the API. There is no new version yet, but I fixed it in the meantime by changing the requirements in the manifest to 
`"requirements": ["git+https://github.com/platysma/vienna-smartmeter.git@main#vienna-smartmeter==0.3.3"],`
