### ISSUE TITLE
Login doesn't work?

### ISSUE THREAD

**Issue by salzrat** [platysma/hass-vienna-smartmeter#68]
I've tried to install the component via the instructions. When I add it, it asks me for username and login. I provide the logwien username and login, but then I just get a red exclamation mark, and in the log the following error:

Traceback (most recent call last): File "/config/custom_components/vienna_smartmeter/config_flow.py", line 87, in _test_credentials await client.refresh_token() File "/usr/local/lib/python3.9/site-packages/vienna_smartmeter/_async/client.py", line 80, in refresh_token "code": await self._get_auth_code(), File "/usr/local/lib/python3.9/site-packages/vienna_smartmeter/_async/client.py", line 59, in _get_auth_code action = await self._get_login_action() File "/usr/local/lib/python3.9/site-packages/vienna_smartmeter/_async/client.py", line 55, in _get_login_action return tree.xpath("(//form/@action)")[0] IndexError: list index out of range

Should this work? Any way I could debug this?
Thanks!

**Comment by staudima** [comment]
Same to me!!

**Comment by klaus1k** [comment]
sadly it's the same with me. Seems to have appeared with the introduction of logwien. Any chance we could help resolve that problem?
Aside from that it's an awesome integration!

**Comment by h0jeZvgoxFepBQ2C** [comment]
Is this fixed already?

**Comment by salzrat** [comment]
I moved to another integration, "WienerNetzeSmartmeter", which works...

**Comment by h0jeZvgoxFepBQ2C** [comment]
Ah thanks, I also just found it, works fine: https://github.com/DarwinsBuddy/WienerNetzeSmartmeter
